pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo "Клон репо"
                checkout scm
            }
        }

        stage('Start PostgreSQL') {
            steps {
                echo " PostgreSQL контейнер"
                sh '''
                    docker rm -f pg_test || true

                    docker run -d --name pg_test \
                        -e POSTGRES_USER=testuser \
                        -e POSTGRES_PASSWORD=testpassword \
                        -e POSTGRES_DB=testdb \
                        -p 5432:5432 \
                        postgres:15

                    echo "сліп щоб підняти "
                    sleep 10
                '''
            }
        }

        stage('Install Python') {
            steps {
                echo " Python"
                sh '''
                    apt-get update
                    apt-get install -y python3 python3-pip python3-venv
                '''
            }
        }

        stage('Install deps') {
            steps {
                echo " Всякі депенденсі"
                sh '''
                    python3 -m venv .venv
                    . .venv/bin/activate
                    pip install --upgrade pip
                    pip install -r lesson_29/requirements.txt
                '''
            }
        }

        stage('Run tests') {
            steps {
                echo " pytest"
                sh '''
                    . .venv/bin/activate
                    pytest lesson_29/tests --alluredir=allure-results
                '''
            }
        }

        stage('Allure report') {
            steps {
                echo " Allure"
            }
            post {
                always {
                    allure([
                        includeProperties: false,
                        jdk: '',
                        results: [[path: 'allure-results']]
                    ])
                }
            }
        }
    }

    post {
        always {
            echo "Очищення PostgreSQL "
            sh 'docker rm -f pg_test || true'

            emailext(
                subject: "Pipeline статус",
                body: "Тести виконано",
                to: "songwriterm77@icloud.com"
            )
        }
    }
}
