pipeline {
    agent none

    stages {

        stage('Checkout') {
            agent any
            steps {
                echo "Клон репо"
                checkout scm
            }
        }

        stage('Run tests in Python Docker') {
            agent {
                docker {
                    image 'python:3.12'
                }
            }
            steps {
                echo "Запускаємо тести"
                sh '''
                    pip install --upgrade pip
                    pip install -r lesson_29/requirements.txt
                    pytest lesson_29/tests --alluredir=allure-results
                '''
            }
            post {
                always {
                    allure([
                        includeProperties: false,
                        jdk: '',
                        results: [[path: 'allure-results']]
                    ])
                }
            }
        }
    }

    post {
        always {
            emailext(
                subject: "Pipeline Complete",
                body: "Allure.",
                to: "songwriterm77@icloud.com"
            )
        }
    }
}
