pipeline {
    agent {
        docker {
            image 'python:3.12'
            args '-u root --privileged -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    stages {

        stage('Checkout') {
            steps {
                echo "Клонуємо репозиторій"
                checkout scm
            }
        }

        stage('Start PostgreSQL (Docker)') {
            steps {
                sh '''
                    echo ">>>> Стартуємо PostgreSQL через Docker"

                    docker rm -f pg_test || true

                    docker run -d --name pg_test \
                        -e POSTGRES_USER=testuser \
                        -e POSTGRES_PASSWORD=testpassword \
                        -e POSTGRES_DB=testdb \
                        -p 5432:5432 \
                        postgres:15

                    echo ">>>> Чекаємо 10 секунд"
                    sleep 10
                '''
            }
        }

        stage('Install deps') {
            steps {
                sh '''
                    echo ">>>> Інсталюємо залежності"

                    python -m venv .venv
                    . .venv/bin/activate

                    pip install --upgrade pip
                    pip install -r lesson_29/requirements.txt
                '''
            }
        }

        stage('Run tests') {
            steps {
                sh '''
                    echo ">>>> Запускаємо pytest"

                    . .venv/bin/activate
                    pytest lesson_29/tests --alluredir=allure-results
                '''
            }
        }

        stage('Allure report') {
            steps {
                echo "Генеруємо Allure"
            }
            post {
                always {
                    allure([
                        includeProperties: false,
                        jdk: '',
                        results: [[path: 'allure-results']]
                    ])
                }
            }
        }
    }

    post {
        always {
            sh 'docker rm -f pg_test || true'

            emailext(
                subject: "Pipeline статус",
                body: "Тести виконано успішно",
                to: "songwriterm77@icloud.com"
            )
        }
    }
}
